version: "3.8"
services:
  db:
    image: mysql:8.0-debian
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: myrootpassword

  web:
    build: .
    command: flask db upgrade && flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - ./.env
    depends_on:
      - db

volumes:
  mysql_data: